import { ThemeVariables } from "../../@types/theme";

export default function ({}: ThemeVariables) {
  return {
    logo: require("./assets/images/logo.png"),
    arrow: require("./assets/images/arrow.png"),
    bank: require("./assets/images/bank.png"),
    money: require("./assets/images/Money.png"),
    trash: require("./assets/images/trash.png"),
    loginIcon: require("./assets/images/loginIcon.png"),
    list: require("./assets/images/list.png"),
    logo_white: require("./assets/images/logo-white.png"),
    card: require("./assets/images/card.png"),
    wallet: require("./assets/images/wallet.png"),
    icon: require("./assets/images/icon.png"),
    line: require("./assets/images/line.png"),
    chip: require("./assets/images/card-chip.png"),
    // utradeLogo:require('./assets/images/utradelogistic-logo.png'),
    // pod: require('./assets/images/pod.png'),
    // startup:{
    //   backImage:require('./assets/images/splash_icon.png'),
    //   icon:require('./assets/images/icon.png'),
    //   be_human:require('./assets/images/letsbehuman.png'),
    // },
    // onboard:{
    //   iconSmall:require('./assets/images/icon-small.png'),
    //   yellowBanner:require('./assets/images/yellow-banner.png'),
    //   yellowBridge:require('./assets/images/yellow-bridge.png'),
    //   blueBanner:require('./assets/images/blue-banner.png'),
    //   blueBridge:require('./assets/images/blue-bridge.png'),
    //   pinkBanner:require('./assets/images/pink-banner.png'),
    //   pinkBridge:require('./assets/images/pink-bridge.png'),
    //   getStartedGif:require('./assets/images/Get-started.gif'),
    //   waiting:require('./assets/images/waiting.png'),
    // },
    // usertype:{
    //   mobilewithtruck:require('./assets/images/mobiletruck.png'),
    //   Driver:require('./assets/images/driver.png'),
    //   Client:require('./assets/images/user.png'),
    //   Transporter:require('./assets/images/transporter.png'),
    // },
    // signup:{
    //   fb:require('./assets/images/facebook.png'),
    //   google:require('./assets/images/google-plus.png'),
    //   twitter:require('./assets/images/twitter.png'),
    // },
    // customDrawer:{
    //   user:require('./assets/images/user-profile.jpg'),
    //   header:require('./assets/images/drawerhead.png'),
    // },
    // homeScreen:{
    //   givingFood:require('./assets/images/givingfood.png'),
    //   givingCoin:require('./assets/images/givingcoin.png'),
    //   givingCloths:require('./assets/images/givingcloths.png'),
    //   givingMoney:require('./assets/images/givingmoney.png'),
    //   activeJob:require('./assets/images/jobtruck.png'),
    //   loadHistory:require('./assets/images/loadHistory.png'),
    //   addDriver:require('./assets/images/addDriver.png'),
    //   list:require('./assets/images/list.png'),
    //   menu:require('./assets/images/menu.png'),
    //   chat:require('./assets/images/chat.png'),
    // },
    // sparkles: {
    //   topLeft: require('./assets/images/sparkles-top-left.png'),
    //   top: require('./assets/images/sparkles-top.png'),
    //   topRight: require('./assets/images/sparkles-top-right.png'),
    //   right: require('./assets/images/sparkles-right.png'),
    //   bottomRight: require('./assets/images/sparkles-bottom-right.png'),
    //   bottom: require('./assets/images/sparkles-bottom.png'),
    //   bottomLeft: require('./assets/images/sparkles-bottom-left.png'),
    // },
    // icons: {
    //   colors: require('./assets/images/colorswatch.png'),
    //   send: require('./assets/images/send.png'),
    //   translate: require('./assets/images/translate.png'),
    //   utradeTruck:require('./assets/images/utrade-truck1.png'),
    //   utradeSmallTruck:require('./assets/images/utrade-sm-truck.png'),
    //   route_white:require('./assets/images/route-white.png'),
    //   route_black:require('./assets/images/route-blacks.png'),
    // },
  };
}
